version: '2'
services:
### brute ###########################################
    brute:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./brute:/var/www/html/:ro
        ports:
            - "${BRUTE_PORT}:80"
        expose:
            - "80"
        restart: always

### bulletin ########################################
    bulletin:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./bulletin_board:/var/www/html/
            - ./tool/forum-adm/:/home/node/:ro
        ports:
            - "${BULLETIN_PORT}:80"
        expose:
            - "80"
        restart: always

### download ########################################
    download:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./download_center:/var/www/html/
        ports:
            - "${DOWNLOAD_PORT}:80"
        expose:
            - "80"
        restart: always

### sqli ############################################
    sqli:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./sqli:/var/www/html/:ro
        ports:
            - "${SQLI_PORT}:80"
        expose:
            - "80"
        restart: always
          
### ping ############################################
    ping-php:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./ping-php:/var/www/html/:ro
        ports:
            - "${PING_PORT}:80"
        expose:
            - "80"
        restart: always

### md5 ####################################################
    md5:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./md5:/var/www/html/:ro
        ports:
            - "${MD5_PORT}:80"
        expose:
            - "80"
        restart: always

### login2 #################################################
    login2:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./login2:/var/www/html/:ro
        ports:
            - "${LOGIN2_PORT}:80"
        expose:
            - "80"
        restart: always

### login1 #################################################
    login1:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./login1:/var/www/html/:ro
        depends_on:
            - login1_mysql
        ports:
            - "${LOGIN_PORT}:80"
        expose:
            - "80"
        restart: always

### login1_mysql ############################################
    login1_mysql:
        image: mysql:${LOGIN1_MYSQL_VERSION}
        container_name: mysql-container
        network_mode: "bridge"
        ports:
          - "${LOGIN1_MYSQL_PORT}:3306"
        volumes:
          - ./login1/wargame.backup.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
          MYSQL_ROOT_PASSWORD: "qwertyQWERTY"
          MYSQL_DATABASE: "wargame"
          MYSQL_USER: "wargame"
          MYSQL_PASSWORD: "qwertyQWERTY"

### http_header ############################################
    http_header:
        image: richarvey/nginx-php-fpm:latest
        network_mode: "bridge"
        volumes:
            - ./http_header:/var/www/html/:ro
        ports:
            - "${HTTP_HEADER_PORT}:80"
        expose:
            - "80"
        restart: always
